version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "avelino"
    labels:
      - "clojure"
      - "dependencies"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "avelino"
    labels:
      - "github-actions"
      - "dependencies"
