(ns training-personal-data.strava.endpoints.activities.api
  (:require [training-personal-data.strava.api :as api]
            [cheshire.core :as json]))

(defn fetch [token page per-page]
  (api/fetch-activities token page per-page))

(defn normalize [activity]
  {:id (:id activity)
   :name (:name activity)
   :distance (:distance activity)
   :moving_time (:moving_time activity)
   :elapsed_time (:elapsed_time activity)
   :total_elevation_gain (:total_elevation_gain activity)
   :type (:type activity)
   :sport_type (:sport_type activity)
   :start_date (:start_date activity)
   :start_date_local (:start_date_local activity)
   :timezone (:timezone activity)
   :achievement_count (:achievement_count activity)
   :kudos_count (:kudos_count activity)
   :comment_count (:comment_count activity)
   :athlete_count (:athlete_count activity)
   :average_speed (:average_speed activity)
   :max_speed (:max_speed activity)
   :average_watts (:average_watts activity)
   :kilojoules (:kilojoules activity)
   :device_watts (:device_watts activity)
   :has_heartrate (:has_heartrate activity)
   :average_heartrate (:average_heartrate activity)
   :max_heartrate (:max_heartrate activity)
   :elev_high (:elev_high activity)
   :elev_low (:elev_low activity)
   :upload_id (:upload_id activity)
   :external_id (:external_id activity)
   :trainer (:trainer activity)
   :commute (:commute activity)
   :manual (:manual activity)
   :private (:private activity)
   :flagged (:flagged activity)
   :workout_type (:workout_type activity)
   :raw_json (json/generate-string activity)})