name: Cron

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-24.04
    environment: main
    env:
      SUPABASE_HOST: "${{ secrets.SUPABASE_HOST }}"
      SUPABASE_PASSWORD: "${{ secrets.SUPABASE_PASSWORD }}"
      SUPABASE_PORT: "${{ secrets.SUPABASE_PORT }}"
      SUPABASE_USER: "${{ secrets.SUPABASE_USER }}"
      SUPABASE_DB_NAME: "${{ secrets.SUPABASE_DB_NAME }}"
    steps:
      - uses: actions/checkout@v5
      - name: Install babashka
        uses: turtlequeue/setup-babashka@v1.7.0
        with:
          babashka-version: 1.12.196
      - name: Set date range
        run: |
          echo "START_DATE=$(date -d 'yesterday' '+%Y-%m-%d')" >> $GITHUB_ENV
          echo "END_DATE=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
      - name: Sync Oura Ring data
        env:
          OURA_TOKEN: "${{ secrets.OURA_TOKEN }}"
        run: bb run:oura $START_DATE $END_DATE
      - name: Sync Wahoo data
        env:
          WAHOO_CLIENT_ID: "${{ secrets.WAHOO_CLIENT_ID }}"
          WAHOO_CLIENT_SECRET: "${{ secrets.WAHOO_CLIENT_SECRET }}"
          WAHOO_REDIRECT_URI: "${{ secrets.WAHOO_REDIRECT_URI }}"
          WAHOO_REFRESH_TOKEN: "${{ secrets.WAHOO_REFRESH_TOKEN }}"
        run: bb run:wahoo $START_DATE $END_DATE
