name: cron
on:
  schedule:
    - cron:  '0 */3 * * *'
  push:
    branches:
      - 'main'

jobs:
  job:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.7.0
        with:
          babashka-version: 1.12.196
      - name: babashka deps
        run: bb prepare
      - name: get ouraring data
        env:
          OURA_TOKEN: '${{ secrets.OURA_TOKEN }}'
          SUPABASE_HOST: '${{ secrets.SUPABASE_HOST }}'
          SUPABASE_PASSWORD: '${{ secrets.SUPABASE_PASSWORD }}'
          SUPABASE_PORT: '${{ secrets.SUPABASE_PORT }}'
          SUPABASE_USER: '${{ secrets.SUPABASE_USER }}'
          SUPABASE_DB_NAME: '${{ secrets.SUPABASE_DB_NAME }}'
        run: |
          START_DATE=$(date -d "yesterday" '+%Y-%m-%d')
          END_DATE=$(date '+%Y-%m-%d')
          bb run:oura $START_DATE $END_DATE
