name: cron
on:
  schedule:
    - cron:  '0 */3 * * *'
  push:
    branches:
      - 'main'

jobs:
  job:
    runs-on: ubuntu-latest
    environment: bot
    timeout-minutes: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.7.0
        with:
          babashka-version: 1.12.196
      - name: babashka deps
        run: bb prepare
      - name: get ouraring data
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: '0'
          OURA_TOKEN: '${{ secrets.OURA_TOKEN }}'
        run: |
          START_DATE=$(date '+%Y-%m-%d')
          bb -cp src -m training-personal-data.ouraring $START_DATE $START_DATE
