name: Weekly Health Insights

on:
  schedule:
    # Runs every Monday at 08:00 UTC
    - cron: "0 8 * * 1"
  workflow_dispatch: # Allows manual execution

jobs:
  generate-insights:
    runs-on: ubuntu-24.04
    environment: main
    steps:
      - uses: actions/checkout@v4
      - name: Install babashka
        uses: turtlequeue/setup-babashka@v1.7.0
        with:
          babashka-version: 1.12.196
      - name: Generate weekly health insights
        env:
          SUPABASE_HOST: "${{ secrets.SUPABASE_HOST }}"
          SUPABASE_PASSWORD: "${{ secrets.SUPABASE_PASSWORD }}"
          SUPABASE_PORT: "${{ secrets.SUPABASE_PORT }}"
          SUPABASE_USER: "${{ secrets.SUPABASE_USER }}"
          SUPABASE_DB_NAME: "${{ secrets.SUPABASE_DB_NAME }}"
          OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
        run: |
          # Calculate the previous Sunday's date (day before Monday execution)
          SUNDAY_DATE=$(TZ=UTC date -d "yesterday" '+%Y-%m-%d')
          echo "Generating insights for week ending on: $SUNDAY_DATE"

          # Execute the weekly insights command
          bb -m training-personal-data.insights.week $SUNDAY_DATE
